tags:
  - Products
summary: Get a list of all products
description: Returns an array of all available products in the store.
responses:
  200:
    description: A list of products.
    schema:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            description: Product ID.
          name:
            type: string
            description: Product name.
          description:
            type: string
            description: Product description.
          price:
            type: number
            format: float
            description: Product price.
          category:
            type: string
            description: Category Name.
          image:
            type: string
            description: Product image URL.
