tags:
  - Products
summary: Add a new product
description: Creates a new product. Requires the user to be logged in.
parameters:
  - in: body
    name: body
    required: true
    schema:
      type: object
      required:
        - name
        - description
        - price
        - category
      properties:
        name:
          type: string
          description: The name of the new product.
          example: "Laptop Pro"
        description:
          type: string
          description: A detailed description of the product.
          example: "A powerful laptop for professionals."
        price:
          type: number
          format: float
          description: The price of the product.
          example: 1299.99
        category:
          type: integer
          description: The ID of the category to which the product belongs.
          example: 1
        image:
          type: string
          description: The URL of the product image.
          example: "https://example.com/product-image.jpg"
responses:
  201:
    description: Product added successfully.
  400:
    description: Invalid data provided.
  401:
    description: Unauthorized, user is not logged in.
